name: Status Check

on:
  pull_request:
    branches: [ main, master ]

jobs:
  status-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Validate project structure
      run: |
        echo "Checking project structure..."
        test -f "app/build.gradle" || exit 1
        test -f "build.gradle" || exit 1
        test -f "settings.gradle" || exit 1
        test -f "gradlew" || exit 1
        test -f "app/src/main/AndroidManifest.xml" || exit 1
        echo "Project structure is valid!"
        
    - name: Check Gradle wrapper
      run: ./gradlew --version
      
    - name: Validate Gradle configuration
      run: ./gradlew projects